version: '2.4'

volumes:
  db:
  server_data:
  front:

x-server-service: &default-server-service
  build:
    context: ..
    dockerfile: ./docker/dc_dev_config/server/Dockerfile
  volumes:
    - server_data:/data
    - ../migrations:/workbench/migrations
    - ../wb:/workbench/wb
    - ../config:/workbench/config
    - ../model_analyzer/model_analyzer:/workbench/model_analyzer
    - ../utils:/workbench/utils
    - ../workbench.py:/workbench/workbench.py:consistent
  environment:
    - &server-root SERVER_ROOT=/workbench
  env_file:
    - ./dc_dev_config/server/environment.env
  restart: on-failure

services:
  rabbitmq:
    image: library/rabbitmq:3.8.5-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=openvino
      - RABBITMQ_DEFAULT_PASS=openvino
      - RABBITMQ_DEFAULT_VHOST=openvino_vhost
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    restart: on-failure

  postgres:
    image: library/postgres:12.2
    environment:
      - POSTGRES_USER=workbench
      - POSTGRES_PASSWORD=openvino
      - POSTGRES_DB=workbench
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    restart: on-failure

  nginx:
    build:
      context: ..
      dockerfile: ./docker/dc_dev_config/nginx/Dockerfile
    ports:
      - "5675:80"
    volumes:
      - server_data:/data
      - front:/front
      - ./dc_dev_config/nginx/app.conf:/etc/nginx/conf.d/default.conf.template
      - ./dc_dev_config/nginx/proxy_params_ws:/etc/nginx/proxy_params_ws
      - ../nginx/security.conf:/etc/nginx/snippets/security.conf
    environment:
      - SERVER_ADDR=server
    restart: on-failure

  client:
    build:
      context: ../client
      dockerfile: ./automation/dc_dev_config/Dockerfile
    volumes:
      - front:/front

  server:
    <<: *default-server-service
    ports:
      - "127.0.0.1:8001:8000"
    environment:
      - CONTAINER_TYPE=web
      - *server-root

  celery:
    <<: *default-server-service
    environment:
      - CONTAINER_TYPE=celery
      - *server-root
